### ISSUE TITLE
Quick Start update for permission denied error

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-provider-for-terraform#17]
**What would you like to be added**:

Update Quick Start to account for any permission denied error message (need to change permission to 0774)

**Why is this needed**:

When manually installing a provider the end user can potentially run into this error message 

```
Error: Error asking for user input: 1 error(s) occurred:

* provider.rubrik: fork/exec /Users/andrewdraper/.terraform.d/plugins/terraform-provider-rubrik: permission denied
```

**Comment by mo6020** [comment]
Fixed in PR31 - https://github.com/rubrikinc/rubrik-provider-for-terraform/pull/31
