### ISSUE TITLE
Terraform v.0.12 Beta Validation

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-provider-for-terraform#29]
**Describe the solution you'd like**

Validate the Rubrik Provider on Terraform v.0.12 Beta 1

**Additional context**

0.12 is a major upgrade for Terraform. We need to validate our modules against them as earlier as possible. 

Workflow:

1.  Download the Beta
2. run `terraform init`
3. run `terraform 0.12upgrade`
4. run `terraform plan` and report back any issues

**Comment by mcozzo** [comment]
`# ls ~/.terraform.d/plugins/darwin_amd64
- terraform-provider-aws
- terraform-provider-panos
- terraform-provider-rubrik `

`# terraform init
Initializing modules...
- aws_config in modules/aws
< Rubrik not listed > 
Terraform has been successfully initialized!`

`# terraform 0.12upgrade
...
Error: failed to load provider "rubrik": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]`

I've downloaded the rubrik plugin a number of times, with the same result. Why isn't the rubrik plugin listed as an official provider through Terraform? 
- https://www.terraform.io/docs/providers/
- http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/

**Comment by RoxieAtRubrik** [comment]
To address the question around being listed as an official provider - this is currently in the works. Our provider is going through validation with the Hashicorp team. We hope to have it listed very soon.

**Comment by shamsway** [comment]
Addressed by #41
