### ISSUE TITLE
Incompatible API version with plugin

### ISSUE THREAD

**Issue by mikenelson-io** [rubrikinc/rubrik-provider-for-terraform#34]
**Expected Behavior**

Executing AWS CloudOn Quick Start example should complete

**Current Behavior**

With Terraform 0.12.4 and AWS provider 2.19.0, I receive an error when running terraform validate. 

**Failure Information (for bugs)**

_"Error: Failed to instantiate provider "rubrik" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client version: [5]"_

* Use verbose outputs to capture any debug information.
```
Paste into a code block.
```

**Steps to Reproduce**

Run terraform validate against quick start code

* Use numbered list.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version of project.
* Version of dependencies.
* Version of operating system.

**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.

```
Paste into a code block.
```

**Comment by drew-russell** [comment]
We need to update the code base to support v0.12. Being tracked here https://github.com/rubrikinc/rubrik-provider-for-terraform/issues/29

**Comment by shamsway** [comment]
Addressed by #41
