### ISSUE TITLE
Create Unit test for cluster_version function

### ISSUE THREAD

**Issue by rfitzhugh** [rubrikinc/rubrik-provider-for-terraform#37]
**Is your feature request related to a problem? Please describe.**

There are currently no unit test for this functions, proper unit tests should be written for this function so we can make this part of the CI/CD pipeline. This will provide more confidence when writing additional functionality or fixing bugs in the provider and is required for certification.

Unit tests should be created for the following function:

* `cluster_version`

**Describe alternatives you've considered**

Manually testing function when adding functionality

**Comment by shamsway** [comment]
Resolved by #46
